name: ACO Export Static Site to GitHub Pages

on:
  workflow_dispatch:  # Run manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build static site
        run: npm run build

      - name: Copy static output to export folder
        run: |
          rm -rf exported-static-site
          mkdir exported-static-site
          cp -r out/* exported-static-site/

      - name: Commit exported site to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add exported-static-site
